### PR TITLE
Fix for duplicate driver instances

### PR DESCRIPTION
**Pull request by carloVentrella**

### CODE REVIEW

**Comment by dbonino** [comment]
Thanks, Carlo, I've realized that the current structure of Modbus drivers was outdated and it was lacking a fix for duplicate instances, almost equals to the one you suggested, which, instead, is present in other technology drivers. I've completely updated the driver structure and added the fix. You can find the updated code on the branch named latest-structure-patch. Could you please test if the drivers in the branch fix also your issue?

**Comment by carloVentrella** [comment]
Sure Dario, I'll check it as soon as possible.

**Comment by carloVentrella** [comment]
Hi Dario, I've tested the drivers and I can confirm that this version solves the problem of duplicate driver instances.

**Comment by dbonino** [comment]
Issues fixed by commit f16496e

**Pull request closed without merging**
